# 프로젝트 root/docker-compose.yml
version: '3.7'

services:

  frontend:
    image: frontend-react
    build:
      context: frontend/imaginary-playground
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "443:443"
    # [인증서 파일 저장 경로]:/var/www/html
    volumes:
      - /home/ubuntu/docker-volume/pem:/var/www/html
    container_name: "frontend"


  backend:
    image: backend-spring
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - /home/ubuntu/docker-volume/pem:/root
    container_name: "backend"
