/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import * as THREE from '../three'

export default function Whale2(props) {

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(window.innerWidth, window.innerHeight)
    document.body.appendChild(renderer.domElement)

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/Whale.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions);
    actions.Swim.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="WhaleArmature">
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone001} />
          <primitive object={nodes.Bone006} />
          <primitive object={nodes.Bone007} />
          <primitive object={nodes.Bone010} />
          <primitive object={nodes.Bone011} />
          <skinnedMesh name="Whale" geometry={nodes.Whale.geometry} material={materials.Whale} skeleton={nodes.Whale.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Whale.gltf')

